language: python
env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.6"

branches:
  only:
  - master

install:
  - wget ${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info -a
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build anaconda-client numpy pytables git
  - conda config --add channels conda-forge
  - conda config --add channels pyiron
  - conda config --set anaconda_upload yes
  - conda install -y -c conda-forge -c pyiron pyiron sphinx nbsphinx lammps ipywidgets

script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - cd .. 
  - git clone --recurse-submodules https://github.com/pyiron/MetaRepo.git
  - git clone https://jan-janssen:${GH_TOKEN}@github.com/pyiron/pyiron.github.io.git
  - git clone https://github.com/pyiron/pyiron-resources.git
  - cd pyiron.github.io
  - git rm -r *
  - touch .nojekyll
  - echo "[DEFAULT]\nTOP_LEVEL_DIRS = $PWD\nRESOURCE_PATHS = $PWD/pyiron-resources" > ~/.pyiron
  - cd ../MetaRepo
  - for d in $(ls -d pyiron*); do sphinx-apidoc -f -o ../pyiron_docs/apidoc $d/$d; done
  - cd ../pyiron_docs
  - sphinx-build -b html ./ ../pyiron.github.io
  - cd ..
  
after_success:
  - cd pyiron.github.io
  - git add -A 
  - git commit -m "Build documentation on $HOSTNAME" 
  - git push --quiet --set-upstream github-token 
