language: python
env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.6"

branches:
  only:
  - master

install:
  - wget ${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info -a
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels pyiron
  - conda update -q conda
  - conda install -y -c conda-forge numpy pytables git sphinx nbsphinx ipywidgets sphinx_rtd_theme pathlib2 pandas h5py sqlalchemy h5io ase spglib pylint Graphviz psutil

script:
  - git config --global user.email "${GH_EMAIL}"
  - git config --global user.name "${GH_USER}"
  - git submodule update --init --recursive
  - git submodule foreach git pull origin master
  - cd .. 
  - git clone --recurse-submodules https://github.com/pyiron/MetaRepo.git
  - git clone https://github.com/pyiron/pyiron-resources.git
  - mkdir pyiron.github.io
  - cd pyiron.github.io
  - touch .nojekyll
  - echo -e "[DEFAULT]\nPROJECT_PATHS = $PWD\nRESOURCE_PATHS = $PWD/pyiron-resources" > ~/.pyiron
  - echo -e "# Build Status\n\nThis repository is automatically updated based on the changes in https://github.com/pyiron/pyiron_docs .\n[![Build Status](https://travis-ci.org/pyiron/pyiron_docs.svg?branch=master)](https://travis-ci.org/pyiron/pyiron_docs)" > README.md
  - cd ../MetaRepo
  - git submodule update --init --recursive
  - git submodule foreach git pull origin master
  - for d in $(ls -d pyiron*); do export PYTHONPATH=$(pwd)/$d:$PYTHONPATH; done
  - for d in $(ls -d pyiron*); do sphinx-apidoc -f -o ../pyiron_docs/apidoc $d/$d; done
  - mkdir uml 
  - cd uml
  - for d in $(ls -d ../pyiron*/pyiron*/); do cp -r $d $(basename $d); done
  - pyreverse -p pyiron* -o png pyiron
  - cp *.png ../../pyiron.github.io
  - cd ../../pyiron_docs
  - sphinx-build -b html ./ ../pyiron.github.io
  - cd ..

deploy:
  provider: pages
  repo: pyiron/pyiron.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ../pyiron.github.io
  on:
     branch: master
